# Generated by Django 4.0.4 on 2022-05-22 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cargo_colab',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cursos',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='entrega_resultados',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='formacao',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='idade',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='projetos',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='score_colaborador',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='tempo_experiencia',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nome',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.empresa', unique=True),
        ),
    ]
