# Generated by Django 4.0.4 on 2022-05-22 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_empresa_colaborador_cargo_colab_colaborador_cursos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folha_pgto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_extra', models.DecimalField(decimal_places=2, max_digits=10, null=True, unique=True)),
                ('descontos', models.DecimalField(decimal_places=2, max_digits=10, null=True, unique=True)),
                ('atestados', models.DecimalField(decimal_places=2, max_digits=10, null=True, unique=True)),
                ('faltas', models.DecimalField(decimal_places=2, max_digits=10, null=True, unique=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, null=True, unique=True)),
                ('my_date', models.DateField()),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.colaborador')),
            ],
        ),
    ]
