# Generated by Django 4.0.4 on 2022-05-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_folha_pgto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
