# Generated by Django 4.0.4 on 2022-05-23 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_alter_empresa_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nome',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='nota_fiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_date2', models.DateField()),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=10, null=True, unique=True)),
                ('forma_pgto', models.CharField(max_length=255, null=True, unique=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True, unique=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='item_nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=255, null=True, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, null=True, unique=True)),
                ('itemnota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.nota_fiscal')),
            ],
        ),
        migrations.CreateModel(
            name='dpto_empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dpto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.departamento')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.empresa')),
            ],
        ),
    ]
