# Generated by Django 4.0.4 on 2022-05-24 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_cargo_alter_colaborador_departamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='nome',
            new_name='colaborador',
        ),
        migrations.RenameField(
            model_name='folha_pgto',
            old_name='my_date',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='item_nota',
            old_name='itemnota',
            new_name='nota_fiscal',
        ),
        migrations.RenameField(
            model_name='nota_fiscal',
            old_name='my_date2',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='departamento',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cargo',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='rh.cargo'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rh.empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='folha_pgto',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rh.colaborador'),
        ),
        migrations.AlterField(
            model_name='nota_fiscal',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rh.empresa'),
        ),
    ]
