# Generated by Django 4.0.4 on 2022-05-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0008_rename_nome_colaborador_colaborador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
