# Generated by Django 4.0.4 on 2022-05-24 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0009_colaborador_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folha_pgto',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.colaborador'),
        ),
    ]
