# Generated by Django 4.0.4 on 2022-05-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0010_alter_folha_pgto_colaborador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_nota',
            old_name='nota_fiscal',
            new_name='item_nota',
        ),
    ]
